services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    restart: on-failure
    environment:
      PORT:           ${PORT:-3001}
      MONGO_URI:      ${MONGO_URI:-mongodb://mongo:27017/authdb}
      JWT_SECRET:     ${JWT_SECRET:-default_secret}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-3600s}
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    container_name: event-server
    restart: on-failure
    environment:
      PORT:      ${EVENT_PORT:-3002}
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/eventdb}
      JWT_SECRET:        ${JWT_SECRET:-default_secret}
      JWT_EXPIRES_IN:    ${JWT_EXPIRES_IN:-3600s}
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    restart: on-failure
    environment:
      PORT:              ${GATEWAY_PORT:-3000}
      AUTH_SERVICE_URL:  http://auth-server:3001
      EVENT_SERVICE_URL: http://event-server:3002
      JWT_SECRET:        ${JWT_SECRET:-default_secret}
      JWT_EXPIRES_IN:    ${JWT_EXPIRES_IN:-3600s}
    ports:
      - "3000:3000"
    depends_on:
      - auth-server
      - event-server

volumes:
  mongo_data:
